// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function GetDirectoryLevel(arg1:string):Promise<Array<main.FileNode>>;

export function Greet(arg1:string):Promise<string>;

export function OpenWorkspaceDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
