name: Wails build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - platform: 'windows/amd64'
            os: 'windows-latest'
          - platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wails
        uses: host-uk/build@v4.0.0
        with:
          build-name: 'ArchivumMarkdown'
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.23'
          node-version: '20'
